default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: aslan_development

test:
  <<: *default
  database: aslan_test

production:
  <<: *default
  database: aslan_production
  username: your_production_username
  password: your_production_password
  host: your_production_host
